# Generated by Django 4.2.7 on 2025-05-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('khu_vuc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dan_so', models.IntegerField()),
                ('dien_tich', models.FloatField()),
                ('mat_do_dan_so', models.FloatField()),
                ('vung', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'POPULATION',
                'managed': False,
            },
        ),
    ]
